version: '3.1'
services:
  codelitt-challenge:
    image: 'codelitt-challenge:latest'
    build:
      context: .
    container_name: codelitt-challenge
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=codelitt
      - POSTGRES_USER=codelitt
      - POSTGRES_DB=codelitt
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jlysnchez@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin